# Compile the actual application methods with a test-only friend declaration.
# Production never includes this generated copy and has no testing definitions.
set(status_fixture_directory "${CMAKE_CURRENT_BINARY_DIR}/application-status")
file(MAKE_DIRECTORY "${status_fixture_directory}")
file(READ "${PROJECT_SOURCE_DIR}/src/app/main.cpp" application_source)
string(REGEX MATCHALL "class Application final" application_declarations "${application_source}")
list(LENGTH application_declarations declaration_count)
if(NOT declaration_count EQUAL 1)
  message(FATAL_ERROR "Application status fixture requires one exact Application declaration")
endif()
string(REPLACE "class Application final {" "class Application final {\n    friend struct ApplicationStatusTestAccess;" application_test_source "${application_source}")
if(application_test_source STREQUAL application_source)
  message(FATAL_ERROR "Application status fixture could not insert its test-only access declaration")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/app/main.cpp")
file(WRITE "${status_fixture_directory}/application-under-test.inc" "${application_test_source}")
add_executable(idleharbor_application_status_tests "${PROJECT_SOURCE_DIR}/tests/application_status_tests.cpp")
target_include_directories(idleharbor_application_status_tests PRIVATE "${status_fixture_directory}" include "${PROJECT_SOURCE_DIR}/src/app")
target_compile_features(idleharbor_application_status_tests PRIVATE cxx_std_20)
target_compile_definitions(idleharbor_application_status_tests PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(idleharbor_application_status_tests PRIVATE idleharbor_core idleharbor_app_support idleharbor_windows Comctl32 Shell32 Wtsapi32)
idleharbor_configure_msvc(idleharbor_application_status_tests)
add_test(NAME application_status COMMAND idleharbor_application_status_tests)
set_tests_properties(application_status PROPERTIES TIMEOUT 30)

add_executable(idleharbor_compact_ui_tests "${PROJECT_SOURCE_DIR}/tests/compact_ui_tests.cpp"
  "${PROJECT_SOURCE_DIR}/resources/IdleHarbor.rc" "${PROJECT_SOURCE_DIR}/resources/app.manifest")
target_include_directories(idleharbor_compact_ui_tests PRIVATE "${status_fixture_directory}" include "${PROJECT_SOURCE_DIR}/src/app")
target_compile_features(idleharbor_compact_ui_tests PRIVATE cxx_std_20)
target_compile_definitions(idleharbor_compact_ui_tests PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(idleharbor_compact_ui_tests PRIVATE idleharbor_core idleharbor_app_support idleharbor_windows Comctl32 Shell32 Wtsapi32)
idleharbor_configure_msvc(idleharbor_compact_ui_tests)
add_test(NAME compact_ui COMMAND idleharbor_compact_ui_tests)
set_tests_properties(compact_ui PROPERTIES TIMEOUT 30)
