set(session_fixture_directory "${CMAKE_CURRENT_BINARY_DIR}/application-session")
file(MAKE_DIRECTORY "${session_fixture_directory}")
file(READ "${PROJECT_SOURCE_DIR}/src/app/main.cpp" application_source)
string(REGEX MATCHALL "class Application final" application_declarations "${application_source}")
list(LENGTH application_declarations declaration_count)
if(NOT declaration_count EQUAL 1)
  message(FATAL_ERROR "Session fixture requires one exact Application declaration")
endif()
string(REPLACE "class Application final {" "class Application final {\n    friend struct ApplicationSessionTestAccess;" session_test_source "${application_source}")
if(session_test_source STREQUAL application_source)
  message(FATAL_ERROR "Session fixture could not insert test-only access")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/app/main.cpp")
file(WRITE "${session_fixture_directory}/application-session-under-test.inc" "${session_test_source}")
add_executable(idleharbor_session_toolkit_tests "${PROJECT_SOURCE_DIR}/tests/session_toolkit_tests.cpp")
target_include_directories(idleharbor_session_toolkit_tests PRIVATE "${session_fixture_directory}" include "${PROJECT_SOURCE_DIR}/src/app")
target_compile_features(idleharbor_session_toolkit_tests PRIVATE cxx_std_20)
target_compile_definitions(idleharbor_session_toolkit_tests PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(idleharbor_session_toolkit_tests PRIVATE idleharbor_core idleharbor_app_support idleharbor_windows Comctl32 Shell32 Wtsapi32)
idleharbor_configure_msvc(idleharbor_session_toolkit_tests)
add_test(NAME session_toolkit COMMAND idleharbor_session_toolkit_tests)
set_tests_properties(session_toolkit PROPERTIES TIMEOUT 30)
